/* Generated By:JavaCC: Do not edit this line. flowppConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface flowppConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Genesis = 5;
  /** RegularExpression Id. */
  int Fatality = 6;
  /** RegularExpression Id. */
  int Insert = 7;
  /** RegularExpression Id. */
  int InsertIf = 8;
  /** RegularExpression Id. */
  int Smash = 9;
  /** RegularExpression Id. */
  int ShowItToMe = 10;
  /** RegularExpression Id. */
  int GetOverHere = 11;
  /** RegularExpression Id. */
  int Var = 12;
  /** RegularExpression Id. */
  int CharValue = 13;
  /** RegularExpression Id. */
  int Number = 14;
  /** RegularExpression Id. */
  int Backslash = 15;
  /** RegularExpression Id. */
  int LeftParen = 16;
  /** RegularExpression Id. */
  int RightParen = 17;
  /** RegularExpression Id. */
  int Comma = 18;
  /** RegularExpression Id. */
  int Quote = 19;
  /** RegularExpression Id. */
  int Assign = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Genesis\"",
    "\"Fatality\"",
    "\"Insert\"",
    "\"InsertIf\"",
    "\"Smash\"",
    "\"ShowItToMe\"",
    "\"GetOverHere\"",
    "\"Var\"",
    "\"CharValue\"",
    "\"Number\"",
    "\"Backslash\"",
    "\"LeftParen\"",
    "\"RightParen\"",
    "\"Comma\"",
    "\"Quote\"",
    "\"Assign\"",
  };

}
